######################## default configuration ####################
baseURL = "https://datasciencia.com"
languageCode = "en-us"
title = "Datasciencia | Data Science from Ground-Up"
theme = "liva-liva"
summaryLength = "10"
paginate = 6
disqusShortname = "hazeez"
enableRobotsTXT = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.highlight]
    codeFences = false 
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false 
    # lineNumbersInTable = true
    noClasses = false 
    style = "github"
    tabWidth = 4

useChroma = false

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"
  [[params.plugins.css]]
  URL = "plugins/venobox/venobox.css"
  # third party plugin - syntax highlighting
  [[params.plugins.css]]
  URL = "plugins/highlightjs/vs.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/venobox/venobox.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/fuse.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/mark.js"
  [[params.plugins.js]]
  URL = "plugins/search/search.js"
  # third party plugin - syntax highlighting
  [[params.plugins.js]]
  URL = "plugins/highlightjs/highlight.pack.js"

  
############################## navigation ###############################
[menu]
  
  # main menu
  [[menu.main]]
  name = "About"
  URL = "about"
  weight = 1
  
  # [[menu.main]]
  # name = "Post"
  # # URL = "blog"
  # URL = "posts"
  # weight = 2
  
  # [[menu.main]]
  # name = "Contact"
  # URL = "contact"
  # weight = 3

  # footer menu
  [[menu.footer]]
  name = "About"
  URL = "about"
  weight = 1
  
  # [[menu.footer]]
  # name = "Post"
  # URL = "blog"
  # weight = 2
  
  # [[menu.footer]]
  # name = "Contact"
  # URL = "contact"
  # weight = 3

  [[menu.footer]]
  name = "Privacy Policy"
  URL = "privacypolicy"
  weight = 4


#################### default parameters ################################
[params]
logo = "images/logo.png"
home = "Home"
# Meta data
description = "Datasciencia aims to make data science simple with easy tutorials and blog posts for beginners."
author = "hazeez"
# Google Analitycs
googleAnalitycsID = "UA-171575356-1"
# Contact Information
#mobile = "9779988988"
email = "info@datasciencia.com"
location = "India"
# copyright
copyright = "copyright &copy; 2020 [datasciencia](https://datasciencia.com) All Rights Reserved"

# for shortcodes
[markup.goldmark.renderer]
unsafe= true

# Preloader
[params.preloader]
enable = false 
preloader = "" # use .png , .svg or .gif format

# search
[params.search]
enable = true

# enable katex  
[params.math]
enable = true

############################ news letter ########################
[params.newsletter]
enable = true 
title = "Join Our Newsletter"
content = "We occasionally send you email updates on the latest posts, tutorials and book recommendations in Data Science. We have a strict no spam policy and we don't sell any data."

############################# social site ########################
[[params.social]]
title = "facebook"
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "https://www.facebook.com/Datasciencia-110682290664089/"

[[params.social]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "#"

# [[params.social]]
# title = "instagram"
# icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
# link = "#"

# [[params.social]]
# title = "github"
# icon = "ti-github" # themify icon : https://themify.me/themify-icons
# link = "#"

[[params.social]]
title = "linkedin"
icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
link = "#"

############################# sharing options ########################

# Sharing options
  # Comment and uncomment to enable or disable sharing options
[[params.sharingOptions]]
name = "facebook"
icon = "ti-facebook"
url = "https://www.facebook.com/sharer/sharer.php?u=%s"

[[params.sharingOptions]]
name = "twitter"
icon = "ti-twitter-alt"
url = "https://twitter.com/intent/tweet?text=%s"

[[params.sharingOptions]]
name = "linkedin"
icon = "ti-linkedin"
url = "https://www.linkedin.com/shareArticle?mini=true&url=%s&source=LinkedIn"
